name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build tailscale image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          image: fcos-tailscale
          context: tailscale/
          containerfiles: ./tailscale/Dockerfile
