name: "Build image: replace-systemd"

env:
  IMAGE_NAME: "replace-systemd"

on:
  pull_request:
    branches:
      - main
    paths:
      - replace-systemd/*
      - .github/workflows/replace-systemd.yml
  push:
    branches:
      - main
    paths:
      - replace-systemd/*
      - .github/workflows/replace-systemd.yml

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          context: ${{ env.IMAGE_NAME }}
          containerfiles: ${{ env.IMAGE_NAME }}/Containerfile
          image: ${{ env.IMAGE_NAME }}
          layers: false
          oci: true
